### PR TITLE
Typescript Migration complete.

### PR DESCRIPTION
**Pull request by iamsethsamuel**
The Javascript Version is working as before and the Typescript version with all the type are working

There is a new way to import packages that takes full advantage of Typescript

```javascript
import RaveBase from "flutterwave-node-v3/lib/rave.base";
import Settlements from "flutterwave-node-v3/lib/rave.settlements";


const rave = new RaveBase(process.env.PUBLIC_KEY!, process.env.SECRET_KEY!)
//Rave in now pass to the Settlements constructor
const settlements = new Settlements(rave)

 settlements.fetch_all().then(res=>{
    const data = res.data
    console.log(data)
    for(const d of res.data){
        console.log(d.channel,d.app_fee, d.currency,)

    }
})

```

This new method allows for tree shaking the package. 

## I just pray this gets merged

### CODE REVIEW

**Comment by orimdominic** [comment]
Good day @corneliusyaovi 

Is there any reason why this has not been merged yet? Is there any contribution that we can make to make this process faster?

**Comment by alob-mtc** [comment]
Hello @orimdominic @iamsethsamuel this is a fairly large PR and the move to TS if at all needs to be by increment. I hope this helps

**Comment by iamsethsamuel** [comment]
> Hello @orimdominic @iamsethsamuel this is a fairly large PR and the move to TS if at all needs to be by increment, also it would be better to raise an issue first for discussion for a change this significant before raising a PR to avoid the risk of rejection. I hope this helps

It was raised before it was worked upon

**Comment by alob-mtc** [comment]
> > Hello @orimdominic @iamsethsamuel this is a fairly large PR and the move to TS if at all needs to be by increment, also it would be better to raise an issue first for discussion for a change this significant before raising a PR to avoid the risk of rejection. I hope this helps
> 
> It was raised before it was worked upon

Thanks for the clarification, please link the issue in the PR for easy tracking

**Comment by alob-mtc** [comment]
I would really like to see this merge, but a quick glance i see a lot of file changes that don't related to Typescript port, this will make it a lot harder to get this PR merged

**Comment by iamsethsamuel** [comment]
> I would really like to see this merge, but at quick glance i see a lot of file changes that don't related to Typescript port, this will make it a lot harder to get this PR merged

First of can you merge the PR? if yes, then we can work on it to be merged

**Comment by orimdominic** [comment]
On the Flutterwave channel, @corneliusyaovi had already said that this would be worked on later this year because of the other products being focused on

**Pull request closed without merging**
